language: perl

services:
  - docker

before_install:
  - git config user.name "TravisCI"
  - git config user.email $HOSTNAME":not-for-mail@travis-ci.org"
  - docker pull mschout/perl-dzil-mschout:5.26
  - docker pull mschout/modperl:apache-1.3-perl-5.10-mp-1.32
  - docker pull mschout/modperl:apache-2.0.53-perl-5.14.4-mp-2.0.9
  - docker pull mschout/modperl:apache-2.2.31-perl-5.20.3-mp-2.0.9
  - docker pull mschout/modperl:apache-2.4.38-perl-5.20.3-mp-2.0.11

install:
  - docker run -v ${TRAVIS_BUILD_DIR}:/app --workdir=/app mschout/perl-dzil-mschout:5.26 ./scripts/dzil-build --in travis-build

script:
  - docker run -v ${TRAVIS_BUILD_DIR}/travis-build:/app --workdir=/app mschout/modperl:apache-1.3-perl-5.10-mp-1.32 /app/scripts/docker-smoke
  - docker run -v ${TRAVIS_BUILD_DIR}/travis-build:/app --workdir=/app mschout/modperl:apache-2.0.53-perl-5.14.4-mp-2.0.9 /app/scripts/docker-smoke
  - docker run -v ${TRAVIS_BUILD_DIR}/travis-build:/app --workdir=/app mschout/modperl:apache-2.2.31-perl-5.20.3-mp-2.0.9 /app/scripts/docker-smoke
  - docker run -v ${TRAVIS_BUILD_DIR}/travis-build:/app --workdir=/app mschout/modperl:apache-2.4.38-perl-5.20.3-mp-2.0.11 /app/scripts/docker-smoke
